#!/bin/bash
VERSION=$(vmware --version | cut -d ' ' -f 3)
wget https://github.com/mkubecek/vmware-host-modules/archive/workstation-$VERSION.tar.gz
tar -xzf workstation-$VERSION.tar.gz
cd vmware-host-modules-workstation-$VERSION
make
sudo make install
echo "Hoera! Gelukt! Even opnieuw opstarten en klaar is kees. (Hoop ik.)"
